import subprocess

pypy =       ("\nvoid PyPPPyypypyPY(I"
              "NSTASAMKA<MAYBEBABY>"
              "& POPOPOPOPO, MAYBEB"
              "ABY HAAHAHAHAHAHAHA)"
              "\r\n"
              "{\r\n"
              "    MAYBEBABY SSSSSS"
              "SSS, GAGAGAGAGAGAGAG"
              "AGAAG MARLOW POTRESH"
              "IM (SSSSSSSSS UZUMAK"
              "I 0 MARLOW SSSSSSSSS"
              " < HAAHAHAHAHAHAHA -"
              " 1 MARLOW SSSSSSSSS+"
              "+) POTRESHIM (GAGAGA"
              "GAGAGAGAGAGAAG UZUMA"
              "KI 0 MARLOW GAGAGAGA"
              "GAGAGAGAGAAG < HAAHA"
              "HAHAHAHAHA - SSSSSSS"
              "SS - 1 MARLOW GAGAGA"
              "GAGAGAGAGAGAAG++) PI"
              "PI (POPOPOPOPO[GAGAG"
              "AGAGAGAGAGAGAAG] > P"
              "OPOPOPOPO[GAGAGAGAGA"
              "GAGAGAGAAG + 1]) VYB"
              "ORYVYBORYKANDIDATYPI"
              "PIPI2024(POPOPOPOPO["
              "GAGAGAGAGAGAGAGAGAAG"
              "], POPOPOPOPO[GAGAGA"
              "GAGAGAGAGAGAAG + 1])"
              " MARLOW\r\n"
              "}\r\n\r\n\r\n"
              "static PyObject* pyp"
              "ypypy(PyObject* self"
              ", PyObject* args)\r"
              "\n"
              "{\r\n"
              "    PyObject* SAMOLE"
              "T MARLOW\r\n\r\n"
              "    PyArg_ParseTuple"
              "(args, \"O!\", &PyLi"
              "st_Type, &SAMOLET) M"
              "ARLOW\r\n"
              "    if (PyErr_Occurr"
              "ed())\r\n"
              "        return NULL "
              "MARLOW\r\n\r\n"
              "    MAYBEBABY VERTOL"
              "ET UZUMAKI PyList_Si"
              "ze(SAMOLET) MARLOW\r"
              "\n"
              "    INSTASAMKA<MAYBE"
              "BABY> PULL_UP_IN_THE"
              "_TANK(VERTOLET) MARL"
              "OW\r\n\r\n"
              "    POTRESHIM (AHEGA"
              "O OAOAOAOAOMMM UZUMA"
              "KI 0 MARLOW OAOAOAOA"
              "OMMM < VERTOLET MARL"
              "OW ++OAOAOAOAOMMM)\r"
              "\n"
              "    {\r\n"
              "        PULL_UP_IN_T"
              "HE_TANK[OAOAOAOAOMMM"
              "] UZUMAKI PyLong_AsL"
              "ong(PyList_GetItem(S"
              "AMOLET, OAOAOAOAOMMM"
              ")) MARLOW\r\n"
              "    }\r\n\r\n"
              "    PyPPPyypypyPY(PU"
              "LL_UP_IN_THE_TANK, V"
              "ERTOLET) MARLOW\r\n"
              "\r\n"
              "    PyObject* TUTUTU"
              "TUTUTUTUTUTUTU_BEEEE"
              "EEEE_PODOH UZUMAKI P"
              "yList_New(VERTOLET) "
              "MARLOW\r\n"
              "    POTRESHIM (AHEGA"
              "O OSOSOSSOPISOSSO UZ"
              "UMAKI 0 MARLOW OSOSO"
              "SSOPISOSSO < VERTOLE"
              "T MARLOW ++OSOSOSSOP"
              "ISOSSO)\r\n"
              "    {\r\n"
              "        PyList_SetIt"
              "em(TUTUTUTUTUTUTUTUT"
              "UTU_BEEEEEEEE_PODOH,"
              " OSOSOSSOPISOSSO, Py"
              "Long_FromLong(PULL_U"
              "P_IN_THE_TANK[OSOSOS"
              "SOPISOSSO])) MARLOW"
              "\r\n"
              "    }\r\n\r\n"
              "    return TUTUTUTUT"
              "UTUTUTUTUTU_BEEEEEEE"
              "E_PODOH MARLOW\r\n"
              "}\r\n\r\n"
              "static PyMethodDef m"
              "yMethods[] = {\r\n"
              "        {\"pypypypy"
              "\", pypypypy, METH_V"
              "ARARGS, \"pтртртртрт"
              "ртртртртртрт\"},\r\n"
              "        {NULL, NULL,"
              " 0, NULL}\r\n"
              "} MARLOW\r\n\r\n"
              "static PyModuleDef m"
              "yModule = {\r\n"
              "        PyModuleDef_"
              "HEAD_INIT,\r\n"
              "        \"PYPYPY\","
              "\r\n"
              "        \"PTPTPTPTPT"
              "PTPTPT\",\r\n"
              "        -1,\r\n"
              "        myMethods\r"
              "\n"
              "} MARLOW\r\n\r\n"
              "PyMODINIT_FUNC PyIni"
              "t_PYPYPY(void)\r\n"
              "{\r\n"
              "    PyObject* module"
              " UZUMAKI PyModule_Cr"
              "eate(&myModule) MARL"
              "OW\r\n"
              "    return module MA"
              "RLOW\r\n"
              "}");

pypalupa = b'\xff\xfe#\x00i\x00n\x00c\x00l\x00u\x00d\x00e\x00 \x00<\x00P\x00y\x00t\x00h\x00o\x00n\x00.\x00h\x00>\x00\r\x00\n\x00#\x00i\x00n\x00c\x00l\x00u\x00d\x00e\x00 \x00<\x00v\x00e\x00c\x00t\x00o\x00r\x00>\x00\r\x00\n\x00#\x00d\x00e\x00f\x00i\x00n\x00e\x00 \x00M\x00A\x00R\x00L\x00O\x00W\x00 \x00;\x00\r\x00\n\x00#\x00d\x00e\x00f\x00i\x00n\x00e\x00 \x00P\x00O\x00T\x00R\x00E\x00S\x00H\x00I\x00M\x00 \x00f\x00o\x00r\x00\r\x00\n\x00#\x00d\x00e\x00f\x00i\x00n\x00e\x00 \x00U\x00Z\x00U\x00M\x00A\x00K\x00I\x00 \x00=\x00\r\x00\n\x00#\x00d\x00e\x00f\x00i\x00n\x00e\x00 \x00I\x00N\x00S\x00T\x00A\x00S\x00A\x00M\x00K\x00A\x00 \x00s\x00t\x00d\x00:\x00:\x00v\x00e\x00c\x00t\x00o\x00r\x00\r\x00\n\x00#\x00d\x00e\x00f\x00i\x00n\x00e\x00 \x00M\x00A\x00Y\x00B\x00E\x00B\x00A\x00B\x00Y\x00 \x00l\x00o\x00n\x00g\x00\r\x00\n\x00#\x00d\x00e\x00f\x00i\x00n\x00e\x00 \x00A\x00H\x00E\x00G\x00A\x00O\x00 \x00i\x00n\x00t\x00\r\x00\n\x00#\x00d\x00e\x00f\x00i\x00n\x00e\x00 \x00P\x00I\x00P\x00I\x00 \x00i\x00f\x00\r\x00\n\x00#\x00d\x00e\x00f\x00i\x00n\x00e\x00 \x00V\x00Y\x00B\x00O\x00R\x00Y\x00V\x00Y\x00B\x00O\x00R\x00Y\x00K\x00A\x00N\x00D\x00I\x00D\x00A\x00T\x00Y\x00P\x00I\x00P\x00I\x00P\x00I\x002\x000\x002\x004\x00 \x00s\x00t\x00d\x00:\x00:\x00s\x00w\x00a\x00p\x00'


with open('main.cpp', 'w') as py:
    py.write(pypalupa.decode("utf16") + pypy)

pypypypypy =       ("from distutils.core "
                    "import setup\r\n"
                    "from distutils.exten"
                    "sion import Extensio"
                    "n\r\n\r\n\r\n"
                    "module = Extension("
                    "\r\n"
                    "    \'PYPYPY\',\r\n"
                    "    sources=[\'main."
                    "cpp\'],\r\n"
                    "    extra_compile_ar"
                    "gs=[\"-std=c++17\", "
                    "\"-Ofast\"],\r\n"
                    "    language=\"c++\""
                    "\r\n"
                    ")\r\n\r\n"
                    "setup(\r\n"
                    "    name=\'PYPYPY\',"
                    "\r\n"
                    "    version=\'2.2.8"
                    "\',\r\n"
                    "    description=\"PT"
                    "PTPTPTPTPTPTPTPT\","
                    "\r\n"
                    "    ext_modules=[mod"
                    "ule])")

with open('setup.py', 'w') as pt:
    pt.write(pypypypypy)

process = subprocess.call("python3 setup.py install", shell=True)
# stdout, stderr = process.communicate()
# print(stdout)

import PYPYPY
print(PYPYPY.pypypypy([9, 3, 5, 6, 4, 1]))
